### ISSUE TITLE
add install_prereqs.sh

### ISSUE THREAD

**Issue by RussTedrake** [openhumanoids/signal-scope#10]
drake001 was failing because of a missing dependency.  resolved with 

```
brew install pyqwt
```

**Comment by tkoolen** [comment]
+1!

**Comment by patmarion** [comment]
fixed by RobotLocomotion/drake/pull/1287.  For what it's worth, I'm not a fan of per project install_prereqs.sh, I'd rather have package manager dependencies listed in the drake.

**Comment by tkoolen** [comment]
awesome, thanks!

**Comment by rdeits** [comment]
@patmarion +1 

@RussTedrake having all of the dependencies listed at the top level in drake would also allow us to switch to Travis's newer & faster infrastructure, which means faster build times. The new infrastructure does not allow the build to use `sudo`, but does allow us to list all of our needed apt packages in the `.travis.yml` file. We need `sudo` right now in order to invoke all the `install_prereqs` scripts.

**Comment by RussTedrake** [comment]
But i'd be fine if drake's superbuild could report it's list of dependencies for the currently included externals, but want to ensure that:
- the individual pods also know their externals (for use outside of drake)
- drake only lists the externals for the existing externals (i think).  It seems like the list of all possible dependencies would be obnoxious.  No?
